server:
  port: '8089'


management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  config:
    import: configserver:http://localhost:8088
  application:
    name: ORDER-SERVICE

