server:
  port: 8088


spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:/spring-boot-micro-services/config
      label: main

  profiles:
    active: default,native



eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://host.docker.internal:8761/eureka}
  instance:
    preferIpAddress: true